<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<body>

<?php
	//Example 1
	/* sing quotation marks is used to display information */
	echo '<p>This comment has been generated by PHP</p>';
?>

<p>This comment is standard HTML</p>

<?php
	echo '<p>This comment has been generated by PHP</p>';
?>
</body>
</html>